# the following environment variables should be set in Travis:
# - DOCKER_IMAGE                : the name of the docker image  - namespace/THIS:tag - this defaults to `goboil` (this package)
# - DOCKER_NAMESPACE            : the namespace of the docker image - THIS/image_name:tag - this defaults to `zephinezr` (mine)
# - DOCKER_REGISTRY             : the registry of the docker image - THIS/namespace/image_name:tag - set to `docker.io` for Docker Hub
# - DOCKER_REGISTRY_PASSWORD    : password for your docker registry
# - DOCKER_REGISTRY_USERNAME    : username for your docker registry
# - REPO_HTTPS_URL              : your source control repository url in HTTPS format - this will be rebuit into https://${USERNAME}:${TOKEN}@rest.of/your/repo.git
# - REPO_PERSONAL_ACCESS_TOKEN  : your personal access token to your repository for pushing tags
# - REPO_USERNAME               : your username to your repository for pushing tags

sudo: required
language: go
services:
- docker
jobs:
  include:
    - stage: test and build
      if: tag IS NOT present
      script:
      - set -x
      - echo "DOCKER_REGISTRY=not_in_use" > ./Makefile.properties
      - echo "DOCKER_NAMESPACE=not_in_use" >> ./Makefile.properties
      - echo "DOCKER_IMAGE=not_in_use" >> ./Makefile.properties
      - make dep ARGS="ensure -v"
      - make testc
      - make build
    - stage: release
      if: branch = master
      script:
      - set -x
      - echo "DOCKER_REGISTRY=not_in_use" > ./Makefile.properties
      - echo "DOCKER_NAMESPACE=not_in_use" >> ./Makefile.properties
      - echo "DOCKER_IMAGE=not_in_use" >> ./Makefile.properties
      - git remote set-url origin "$(printf -- "${REPO_HTTPS_URL}" | sed -e "s|https://|https://${REPO_USERNAME}:${REPO_PERSONAL_ACCESS_TOKEN}@|g")"
      - git checkout master
      - make version.bump
      - git push --tags
